# Generated by Django 4.2.9 on 2024-02-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
