# Generated by Django 4.2.9 on 2024-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0003_remove_menuitem_menu_name_alter_menuitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
