# Generated by Django 4.2.9 on 2024-02-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0004_menuitem_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_name',
        ),
    ]
